### ISSUE TITLE
Add tabular numbers feature

### ISSUE THREAD

**Issue by rsms** [rsms/interface#10]
Add fixed-width tabular numbers ("tnums") feature

**Comment by rsms** [comment]
<img width="1119" alt="slice 13" src="https://user-images.githubusercontent.com/47046/29655245-3c89d7d6-8865-11e7-824c-89e024ea1d3a.png">

Also for italics of course.

<img width="231" alt="screenshot 2017-08-24 00 42 42" src="https://user-images.githubusercontent.com/47046/29655254-499d28c4-8865-11e7-8563-d5a213288308.png">

**Comment by terinjokes** [comment]
Thanks @rsms! I meant to create this issue after our Twitter discussion, but I forgot.

**Comment by rsms** [comment]
Next release will also include slashed zero (OpenType feature `zero`) as well as a stylistic set for open digits. All three features can be combined (meaning there will be a glyph for "regular six", "tabular six", "regular six in style-1", "tabular six in style-1", etc.)
