### ISSUE TITLE
Include SIL Open Font License in binary release

### ISSUE THREAD

**Issue by chrissnell** [rsms/interface#11]
I'm making an AUR package for your font so that Arch Linux users can easily install it.   It would make my job a lot easier if you could include the SIL license with the binary release.  (might even be required by the license??)

Something like a LICENSE.TXT file would be perfect.

Such an awesome font!  Thanks!

**Comment by chrissnell** [comment]
I just pulled the license directly from SIL for now but it's super janky and will break the package if SIL changes the license text and/or URL.

Here's my package if you're interested:

**Comment by rsms** [comment]
I'll add it to the release zip archives.

**Comment by rsms** [comment]
Thanks for doing this, by the way 😺

**Comment by rsms** [comment]
If you have installation instructions for Arch Linux, is would be great to include that as well. (Have a look at https://github.com/rsms/interface/tree/master/misc/doc for the mac and win instructions)

**Comment by rsms** [comment]
Included in latest release https://github.com/rsms/interface/releases/tag/v1.2
