### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by fusion2004** [rsms/interface#12]
I think this typeface is very cool. Thank you for releasing it.

What do you think about trying to get it onto Google Fonts?
It looks like they have a contact form for that here: https://docs.google.com/forms/d/e/1FAIpQLSfQ4K1jZc_dtc9JDsWcoye_4-hmzms-CX43EW97lm4RqU1dMA/viewform

(I found this on the FAQ: https://developers.google.com/fonts/faq#i_am_a_type_designer_how_can_i_contribute_to_google_fonts)

**Comment by rsms** [comment]
Yeah, I've looked into that already. I think it might be better to wait until Interface is getting more stable (I'm assuming it's a slow process to get updates onto google fonts.)

**Comment by davelab6** [comment]
We are speeding up the process :) https://github.com/google/fonts/issues/1167

**Comment by rsms** [comment]
Fantastic @davelab6! I'll try to get a version 1.2 out tonight, which will include tabular numbers, slashed zero, more kerning and a name table fix for Windows.

**Comment by rsms** [comment]
The detail police shot it down.

**Comment by davelab6** [comment]
You are required by international law to rename this project due to the trademark, being a hobby project is not an excuse. @dm-dama is asking you nicely, and you ought to honor his request.

**Comment by splorp** [comment]
Renaming a typeface isn’t a huge deal, @rsms … it happens quite regularly within the industry. We can all help you rename the typeface in the codebase, if time and resources are an issue. This is a great project, so let’s all work together to make sure it’s compliant.

**Comment by Kikobeats** [comment]
Renamed was done, so maybe is a good moment right now 😄

**Comment by amio** [comment]
How is this going?

**Comment by MayusYT** [comment]
@rsms Is there any update about the request? I'd really like to include this amazing font as a webfont.

**Comment by inferno986return** [comment]
I would love to see this font on Google Fonts and Google Docs! :-D

**Comment by nicooprat** [comment]
I'd love to get it from Google Fonts too, and I hope we will have the partial language feature which could greatly reduce the font size (~100kb each one) too!
