### ISSUE TITLE
Can't install both Regular and Medium on Windows 7

### ISSUE THREAD

**Issue by y6nH** [rsms/interface#13]
Since Regular and Medium have the same internal name ("Interface"), the second one installed just overwrites the first. The same applies to the italic variants.

**Comment by joestrouth1** [comment]
Same issue exists on Windows 10. Following the installation documentation results in a warning dialog asking me to overwrite; once for "Interface" once for the italics.

**Comment by rsms** [comment]
Hm, this seems like a bug. I know what the issue is and I'll fix it tonight after work.

**Comment by rsms** [comment]
Should be fixed in 1.2 https://github.com/rsms/interface/releases/tag/v1.2

@y6nH @joestrouth1 Can you please verify that release 1.2 works for you?

**Comment by eh8** [comment]
1.2 resolves the issue for me (running Windows 10)
