### ISSUE TITLE
Diagonal arrows

### ISSUE THREAD

**Issue by rxrbln** [rsms/interface#16]
Thank you for the great type! I gave it a try on Linux, and found the diagonal arrows missing used in some software. I believe this are Unicode U+2196, 7, 8, 9

I could try another day if I could add it myself, but maybe this is something that could be copied form the regular, straight arrows easily?

**Comment by rsms** [comment]
<img width="569" alt="screenshot 2017-08-26 16 17 52" src="https://user-images.githubusercontent.com/47046/29745809-24cb36c8-8a7a-11e7-8435-370ee1bb1258.png">
