### ISSUE TITLE
copyfile fails on initial build

### ISSUE THREAD

**Issue by danbahrami** [rsms/interface#20]
## The error

When running `make` to create initial build I get the following error:

```
misc/ufocompile --otf Regular
/Users/dan/Code/interface/src/features.fea
/Users/dan/Code/interface/build/tmp/InterfaceUFO/features.fea
Traceback (most recent call last):
  File "misc/ufocompile", line 95, in <module>
    os.path.join(args.out, 'InterfaceUFO', 'features.fea'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/dan/Code/interface/build/tmp/InterfaceUFO/features.fea'
make: *** [build/tmp/InterfaceTTF/Interface-Regular.ttf] Error 1
```

It appears that at execution time the `build/tmp/InterfaceUFO` directory doesn't exist, which is causing `copyfile` to throw.

The same happens when trying to build a specific font e.g. `make Regular`

## Steps I took
```
$ git clone git@github.com:rsms/interface.git
$ cd interface
$ ./init.sh
$ source './init.sh'
$ make
```

## My system
macOS sierra 10.12.6
Python 2.7.10
Virtualenv 15.1.0

**Comment by danbahrami** [comment]
It's possible that this is caused by the initial run of `./init.sh` failing before it creates the `build/tmp/InterfaceUFO` directory. It fails to install `woff2` for me.

Here's the output
https://gist.github.com/danbahrami/9c5cf809ca1f9e8b93ed4d34da6d89fe

**Comment by rsms** [comment]
Good catch. I'll fix this right away.

**Comment by rsms** [comment]
Fixed. The issue was that I had `*.patch` in the .gitignore and had thus missed to commit the patch. Tested and verified to work on my system in a fresh clone.
