### ISSUE TITLE
Missing U+041A CYRILLIC CAPITAL LETTER KA

### ISSUE THREAD

**Issue by tmcdos** [rsms/interface#22]
Hello
I think I found a couple of issues in the current release version 1.5 - have not checked previous versions and can not build from source.
Can you confirm that issues are not observed on my PC only?

Hinted TTF - **bold**
![hinted_bold](https://user-images.githubusercontent.com/19253115/29922871-14383498-8e60-11e7-9c33-3c50e8271b3b.png)
Hinted TTF - **_bold italic_**
![hinted_bold_italic](https://user-images.githubusercontent.com/19253115/29922870-14373ba6-8e60-11e7-9652-ee91697b225e.png)
Hinted TTF - medium
![hinted_medium](https://user-images.githubusercontent.com/19253115/29922873-143a2866-8e60-11e7-9101-00100c33c462.png)
Hinted TTF - _medium italic_
![hinted_medium_italic](https://user-images.githubusercontent.com/19253115/29922863-142ebde6-8e60-11e7-86a4-62d5922e4145.png)
Hinted TTF - regular
![hinted_regular](https://user-images.githubusercontent.com/19253115/29922857-1428d41c-8e60-11e7-9c4e-85d6e32a1c47.png)
Hinted TTF - _regular italic_
![hinted_regular_italic](https://user-images.githubusercontent.com/19253115/29922868-1434102a-8e60-11e7-8a10-47815cf366c2.png)
OTF - **bold**
![otf_bold](https://user-images.githubusercontent.com/19253115/29922862-142e2066-8e60-11e7-84b8-3bb1d166df06.png)
OTF - **_bold italic_**
![otf_bold_italic](https://user-images.githubusercontent.com/19253115/29922858-14298b32-8e60-11e7-88f4-5b3498e1b86b.png)
OTF - medium
![otf_medium](https://user-images.githubusercontent.com/19253115/29922865-1431a736-8e60-11e7-8d37-e330e5a4cfe4.png)
OTF - _medium italic_
![otf_medium_italic](https://user-images.githubusercontent.com/19253115/29922861-142dbcde-8e60-11e7-8572-63d9aace4514.png)
OTF - regular
![otf_regular](https://user-images.githubusercontent.com/19253115/29922872-1438bb70-8e60-11e7-8ec7-caefcba67a08.png)
OTF - _regular italic_
![otf_regular_italic](https://user-images.githubusercontent.com/19253115/29922856-1427abb4-8e60-11e7-8796-73cb6514322b.png)
TTF - **bold**
![ttf_bold](https://user-images.githubusercontent.com/19253115/29922864-14303770-8e60-11e7-95c4-4196b24b71ec.png)
TTF - **_bold italic_**
![ttf_bold_italic](https://user-images.githubusercontent.com/19253115/29922867-1433c4ee-8e60-11e7-8973-ed1825641772.png)
TTF - medium
![ttf_medium](https://user-images.githubusercontent.com/19253115/29922860-142cbee2-8e60-11e7-8bc3-795297e3f3eb.png)
TTF - _medium italic_
![ttf_medium_italic](https://user-images.githubusercontent.com/19253115/29922859-142b60d8-8e60-11e7-8f56-2c1104129a41.png)
TTF - regular
![ttf_regular](https://user-images.githubusercontent.com/19253115/29922869-14357ea6-8e60-11e7-9ae9-a030516fab46.png)
TTF - _regular italic_
![ttf_regular_italic](https://user-images.githubusercontent.com/19253115/29922866-14323886-8e60-11e7-9c14-ee423d004ca2.png)

**Comment by tmcdos** [comment]
`040C` is for Macedonian and is not among the standard symbols. The one I am talking about is `041A`

**Comment by rsms** [comment]
`040C` was just an example.
So the glyph you're missing is `U+041A CYRILLIC CAPITAL LETTER KA`. Should be easy to add.

**Comment by tmcdos** [comment]
Not only me - all people who will use the font to show Cyrillic texts will miss the symbol.
And this is not the only issue with 1.5 release of the font - as you can see on the screenshots, **Ю** and **Б** also have problems.

**Comment by rsms** [comment]
Relates to #17

**Comment by rsms** [comment]
Added in [release 1.6](https://github.com/rsms/interface/releases/tag/v1.6)

https://rsms.me/interface/glyphs/?g=Kacyr
