### ISSUE TITLE
Adjustments to Cyrillic glyphs U+0411 and U+042E

### ISSUE THREAD

**Issue by tmcdos** [rsms/interface#26]
In version 1.6 of the font there are some issues with the glyphs on codepoints `U+0411` and `U+042E` in different font weights:

TTF hinted - Black:
![black_hinted_ttf](https://user-images.githubusercontent.com/19253115/30072654-b47bb454-9273-11e7-85a7-1814b62d2651.png)

OTF - Black:
![black_otf](https://user-images.githubusercontent.com/19253115/30072656-b48129fc-9273-11e7-887d-23a27745216b.png)

TTF - Black:
![black_ttf](https://user-images.githubusercontent.com/19253115/30072660-b49f565c-9273-11e7-8bf8-17794c312652.png)

OTF - Bold:
![bold_otf](https://user-images.githubusercontent.com/19253115/30072653-b47b3498-9273-11e7-8578-2fc141149a28.png)

TTF - Medium Italic:
![medium_italic_ttf](https://user-images.githubusercontent.com/19253115/30072655-b47d2208-9273-11e7-9255-02fffa78837f.png)

OTF - Medium:
![medium_otf](https://user-images.githubusercontent.com/19253115/30072657-b4829288-9273-11e7-80f7-bd1d6d5a05f8.png)

TTF - Medium:
![medium_ttf](https://user-images.githubusercontent.com/19253115/30072663-b4c23cd0-9273-11e7-91ce-d0a40eec1967.png)

OTF - Regular Italic:
![regular_italic_otf](https://user-images.githubusercontent.com/19253115/30072662-b4bf0ba0-9273-11e7-83a9-5c9210e1b0ba.png)

TTF - Regular Italic:
![regular_italic_ttf](https://user-images.githubusercontent.com/19253115/30072661-b4a77f44-9273-11e7-9d4d-b3958f829536.png)

ITF - Regular:
![regular_otf](https://user-images.githubusercontent.com/19253115/30072658-b4962640-9273-11e7-8a17-d6203f19b156.png)

TTF - Regular:
![regular_ttf](https://user-images.githubusercontent.com/19253115/30072659-b49cde04-9273-11e7-9b3f-8979d607b5ad.png)

**Comment by rsms** [comment]
The "empty bar" seems to be a bug with the software you're using (I can't repro with the CFF outline data in the OTF files — guessing the app you're using doesn't treat winding rules in CFF correctly.)

All the other issues are being resolved and thanks for pointing them out!

**Comment by rsms** [comment]
<img width="397" alt="screenshot 2017-09-12 23 54 57" src="https://user-images.githubusercontent.com/47046/30363700-0ac5340a-9816-11e7-902d-371f5050fb10.png">

<img width="389" alt="screenshot 2017-09-12 23 55 32" src="https://user-images.githubusercontent.com/47046/30363702-0d13aaac-9816-11e7-9b9d-fdc5b388bdfe.png">

<img width="375" alt="screenshot 2017-09-12 23 56 14" src="https://user-images.githubusercontent.com/47046/30363706-0ff47bd4-9816-11e7-981d-de5ac7bdfbfc.png">
