### ISSUE TITLE
Kerning on T glyph is very tight

### ISSUE THREAD

**Issue by rossfishkind** [rsms/interface#27]
Hi there! I just noticed this today after the new release, but it seems that any glyph that fits under a capital T has extremely tight kerning:

![image](https://user-images.githubusercontent.com/331101/30359720-7829f5ea-9801-11e7-9862-bf7e704cc724.png)

It seems a bit off. Thoughts?

**Comment by rsms** [comment]
Good catch.

Kerning primaries to sample and adjust:

```
/A T /L T /a T Hello /ae T /b T /c T /divide T /k T /r Test /s Test /u Test /z Test /v Test /w Test /x Test

Test T/A Test T/AE Test T/C Test T/J Test T/a Test T/c Test T/colon Test T/comma Test T/divide
Test T/dotlessj Test T/eightsub Test T/guillemotleft Test T/guillemotright Test T/m Test T/quotedblbase Test T/s Test T/six Test T/u Test T/v Test T/w Test T/x Test T/z Test T/ampersand
Test T/backslash Test T/four Test T/less Test T/periodcentered Test T/slash Test T/three Test
T/underscore
```

**Comment by rsms** [comment]
Test words for "T" at left:

```
Take Total Table Terms That Time Title To Top Today Tools Travel Training Try Track Trade Type Tickets Thought The This They Their There These Than Them Then Through Those Treatment Tn Td Tm Tp
```

<img width="1247" alt="screenshot 2017-09-12 23 38 07" src="https://user-images.githubusercontent.com/47046/30363023-82e40f04-9813-11e7-8307-c68d955ea57f.png">

<img width="260" alt="screenshot 2017-09-12 23 31 13" src="https://user-images.githubusercontent.com/47046/30363035-89b7b33a-9813-11e7-88fb-3a0055db8f70.png">
