### ISSUE TITLE
"ligibility" spelling, did you mean "eligibility"

### ISSUE THREAD

**Issue by speckz** [rsms/interface#5]
Hi,

In the description you have:

> Interface is a typeface specially designed for user interfaces, with excellent ligibility at small sizes.

Did you mean "eligibility" instead of "ligibility"?

**Comment by gpluess** [comment]
"legibility" ?

**Comment by speckz** [comment]
Ugh, yes, "legibility". Derp, sorry, lack of ☕️!

**Comment by rsms** [comment]
Thanks!

**Comment by nitrofurano** [comment]
i guess "readability" can be used as well?
