### ISSUE TITLE
obliques are not italics

### ISSUE THREAD

**Issue by nitrofurano** [rsms/interface#8]
there is a game at http://thinkingwithtype.com/extras/ ( The Crime:Pseudo Italics ) explaining how obliques should never be named as italics - italics has nothing to do with obliques, it has to do with calligraphic version of a typeface - please, please correct this, and please stop spreading such confusion

**Comment by rsms** [comment]
Thank you for your concern and nitpicking, but I think "italic" is a suitable style name for the following reasons:

1. How do you even spell "oblique"? (I hope you understand the joke)
2. It's common to use an oblique technique (see what I did there) with sans-serif fonts
3. Everyone knows what "italic" is, even if they don't actually know what "italic" means.

So, it's a decision mainly driven by pragmatism.

> Re the game: "This content requires the Flash Player"

**Comment by nitrofurano** [comment]
totally wrong... - sorry if my comment sounds too blunt, but your "decision" (driven by convenience?) is a clear example of "a lie told often enough becomes the 'truth'." - such spreading is indeed a huge negligence
